# Generated by Django 4.1.9 on 2023-05-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0172_larger_power_draw_values'),
        ('circuits', '0042_provideraccount'),
        ('netbox_otn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oms',
            name='circuit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_circuit', to='circuits.circuit'),
        ),
        migrations.AddField(
            model_name='oms',
            name='device_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='oms_device_a', to='dcim.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oms',
            name='device_z',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='oms_device_z', to='dcim.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oms',
            name='frontport_a',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_frontport_a', to='dcim.frontport'),
        ),
        migrations.AddField(
            model_name='oms',
            name='frontport_z',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_frontport_z', to='dcim.frontport'),
        ),
        migrations.AddField(
            model_name='oms',
            name='rearport_a',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_rearport_a', to='dcim.rearport'),
        ),
        migrations.AddField(
            model_name='oms',
            name='rearport_z',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_rearport_z', to='dcim.rearport'),
        ),
    ]
