# Generated by Django 4.1.9 on 2023-05-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0042_provideraccount'),
        ('dcim', '0172_larger_power_draw_values'),
        ('netbox_otn', '0002_oms_circuit_oms_device_a_oms_device_z_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='och',
            name='interface_a',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='och_interface_a', to='dcim.interface'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='och',
            name='interface_z',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='och_interface_z', to='dcim.interface'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='och',
            name='muxport_a',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='och_frontport_a', to='dcim.frontport'),
        ),
        migrations.AddField(
            model_name='och',
            name='muxport_z',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='och_frontport_z', to='dcim.frontport'),
        ),
        migrations.AlterField(
            model_name='oms',
            name='circuit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_circuit', to='circuits.circuit'),
        ),
        migrations.AlterField(
            model_name='oms',
            name='frontport_a',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_frontport_a', to='dcim.frontport'),
        ),
        migrations.AlterField(
            model_name='oms',
            name='frontport_z',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_frontport_z', to='dcim.frontport'),
        ),
        migrations.AlterField(
            model_name='oms',
            name='rearport_a',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_rearport_a', to='dcim.rearport'),
        ),
        migrations.AlterField(
            model_name='oms',
            name='rearport_z',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_rearport_z', to='dcim.rearport'),
        ),
    ]
