# Generated by Django 4.1.9 on 2023-05-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_otn', '0003_och_interface_a_och_interface_z_och_muxport_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oms',
            name='device_a',
        ),
        migrations.RemoveField(
            model_name='oms',
            name='device_z',
        ),
    ]
