# Generated by Django 4.1.9 on 2023-05-29 21:42

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0172_larger_power_draw_values'),
        ('extras', '0092_delete_jobresult'),
        ('netbox_otn', '0004_remove_oms_device_a_remove_oms_device_z'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=50)),
                ('contract', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='planned', max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('interface_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_interface_a', to='dcim.interface')),
                ('interface_z', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_interface_z', to='dcim.interface')),
                ('och', models.ManyToManyField(related_name='client_och', to='netbox_otn.och')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Client Signal',
                'verbose_name_plural': 'Client Signals',
                'ordering': ('name',),
            },
        ),
    ]
